---
- name: Copy file to EC2 instance
  hosts: 18.192.214.248
  become: true  # This is required if you need elevated privileges (sudo)

  tasks:
    - name: Copy file to EC2
      ansible.builtin.copy:
        src: /mnt/c/git/learn/ansible/test.txt  # Path to the local file
        dest: /home/ec2-user/test.txt   # Destination path on the EC2 instance
    - name: Change file permissions
      ansible.builtin.file:
        path: /home/ec2-user/test.txt
        mode: "0755"
